### ISSUE TITLE
Rename from matherhorn to mathegral

### ISSUE THREAD

**Issue by alimfeld** [MathAdmin/mathegral#23]
- [x] Renames in code
- [x] Rename repository
- [x] Reconfigure Cloudflare project  (Setup new Cloudlflare project w/ proper name w/ #24)
- [x] Redesign favicon

**Comment by xandrun** [comment]
@MathAdmin Here some design proposals for the logo/favicon. Anything you like?

![grals](https://user-images.githubusercontent.com/98267673/150684043-61e61797-411d-4830-bb26-862b69173427.png)

**Comment by xandrun** [comment]
New logo version
![gral5-01](https://user-images.githubusercontent.com/98267673/152155694-14b5eb5b-8951-43af-8262-9fb7634b0326.png)

**Comment by MathAdmin** [comment]
Sehr cool! 

Von meinem Xperia™ von Sony-Smartphone gesendet

---- xandrun schrieb ----

**Comment by xandrun** [comment]
Version with old blue: #3272B7
![gral5-01_hellblau](https://user-images.githubusercontent.com/98267673/153933597-37ea3e76-ce65-4479-9b49-6476343dfc59.png)
